config/routes.rb
Rails.application.routes.draw do
  get 'bar/change'
  devise_for :users
  # root 'top#index'
  root to: 'bar#index'

  resources :list, only: %i(new create edit update destroy) do
    resources :card, except: %i(index)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :list

  has_many :category

  validates :title, length: { in: 1..255}
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :card
  # belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :cards, dependent: :destroy
  # has_many :category
  validates :title, length: { in: 1..255 }
end

app/models/percent.rb
class Percent < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :lists, dependent: :destroy
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i(name))
  end

end

app/controllers/bar_controller.rb
class BarController < ApplicationController
  def index
  end

  def change
    puts "##################################"
    puts "change_color action が呼ばれました"
    puts "##################################"

    percent = (params[:percent]).to_i   #intergerに変換

    #データをActiveRecordで保存する
    Percent.create(value:percent)

    #ActiveRecordを用いて合計、平均、最大、最小を計算する
    sum = (Percent.sum(:value)).round(2)
    ave = (Percent.average(:value)).round(2)
    max = Percent.maximum(:value)
    min = Percent.minimum(:value)

    #bootstrapの色を変えるためのパラメータを決定する
    if percent < 30
      color_mode = "progress-bar progress-bar-striped active"
    elsif percent > 70
      color_mode = "progress-bar progress-bar-danger progress-bar-striped active"
    else
      color_mode = "progress-bar progress-bar-success progress-bar-striped active"
    end

    data_hash = {"sum" => sum, "ave" => ave, "max" => max, "min" => min, "color_mode" => color_mode}
    data_json = data_hash.to_json
    puts "data_json:#{data_json}"
    render json: data_json

  end

end

app/controllers/card_controller.rb
class CardController < ApplicationController
 before_action :set_card, only: %i(show edit update destroy)

  def new
    @card = Card.new
    @list = List.find_by(id: params[:list_id])
    @category = Category.all
  end

  def create
    @card = Card.new(card_params)
    if @card.save
      redirect_to :root
    else
      @card.valid?
      render action: :new
    end
  end

  def show
  end

  def edit
    @lists = List.where(user: current_user)

  end

  def update
    if @card.update_attributes(card_params)
      redirect_to :root
    else
      @card.valid?
      render action: :edit
    end
  end

  def destroy
    @card.destroy
    redirect_to :root
  end


  private
    def card_params
      params.require(:card).permit(:title, :memo, :list_id)
    end

    def set_card
      @card = Card.find_by(id: params[:id])
    end
end

app/controllers/list_controller.rb
class ListController < ApplicationController
  before_action :set_list, only: %i(edit update destroy)

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to :root
    else
      @list.valid?
      render action: :new
    end
  end

  def edit
  end

  def update
    if @list.update_attributes(list_params)
      redirect_to :root
    else
      @list.valid?
      render action: :edit
    end
  end

  def destroy
    @list.destroy
    redirect_to :root
  end


private
  def list_params
    params.require(:list).permit(:title).merge(user: current_user)
  end

  def set_list
    @list = List.find_by(id: params[:id])
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @lists = List.where(user: current_user).order("created_at ASC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bar_helper.rb
module BarHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/bar/index.html.erb
<div class= "container">

<div class="page-header">
  <h1>Progress Bar  and  List by Ajax </h1>
</div>

<div class="row">

  <!-- 左半分 -->
  <div class="col-sm-6">

    <!-- 数値入力フォーム -->
    <form class="form-horizontal">
      <div class="form-group">
        <label class="col-sm-2 control-label" for="InputNumber">number</label>
        <div class="col-sm-4">
          <input type="number" class="form-control" id="input_number" placeholder="数値">
        </div>
      </div>
    </form>

    <!-- プログレス・バー -->
    <div class="progress">
      <div class="progress-bar progress-bar-striped active" id="my_bar" role="progressbar" style="width: 20%;">
        20%
      </div>
    </div>

  </div>

  <!-- 右半分 -->
  <div class="col-sm-6">

      <table class="table table-bordered">
        <thead>
          <tr>
            <th>type</th>
            <th>value</th>
          </tr>
        </thead>

        <tbody>
          <tr>
            <th>合計値</th>
            <td id="sum"></td>
          </tr>
          <tr>
            <th>平均値</th>
            <td id="ave"></td>
          </tr>
          <tr>
            <th>最大値</th>
            <td id="max"></td>
          </tr>
          <tr>
            <th>最小値</th>
            <td id="min"></td>
          </tr>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/card/_animation.html.erb
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<script>
const progressBar = function(id){
      const frame = $(id);
      const bar = $('div.progress-bar', frame);
      let current = 0;
      return {
        current: function(){
          return current;
        },
        set: function(n) {
          current = (n > 100) ? 100 : n;
          bar
            .css('width', current + '%')
            .prop('aria-valuenow', current)
            .text(current + '%');
          return this;
        },
        show: function() {
          this.set(0);
          frame.addClass('show');
          bar.addClass('progress-bar-striped progress-bar-animated');
          return this;
        },
        complete: function(){
          bar.removeClass('progress-bar-striped progress-bar-animated');
          return this;
        }
      };
    };
</script>

<script>
 (function($){
      const progress = new progressBar('#progress');
      const btn = $('#btn');

      btn.on('click', function(){
        progress.show();
        btn.prop("disabled", true);

        // 進行状況チェック (チェック間隔は任意...)
        const timer = setInterval(function() {
          const current = progress.current();
          if (current < 100) {
            // バーを進める ※サンプル：0〜10の乱数を加算する
            const n = Math.floor( Math.random() * 11 );
            progress.set(current + n);
          } else {
            // 100%になれば、チェック(繰り返し)を終了する
            progress.complete();
            clearInterval(timer);

            btn
              .text('終了')
              .addClass('btn-outline-success')
              .removeClass('btn-outline-primary');
          }
        }, 200);
      });
    })(jQuery);
</script>

app/views/card/edit.html.erb
<div class="cardeditPgae">
  <div class='container'>
    <%= form_with model: @card, url: { action: :update }, html: { class: 'cardeditForm' } do |f| %>
      <% if @card.errors.any? %>
        <p class="text-danger">タイトルは1～255文字以内で入力してください</p>
      <% end %>
      <div class="cardeditForm_title">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control", placeholder: "カード名" %>
      </div>
      <div class="cardeditForm_memo">
        <%= f.label :memo %>
        <%= f.text_area :memo, class: "form-control", placeholder: "詳細" %>
      </div>
      <div class="cardeditForm_memo">
        <label>リスト名</label>
        <%= select :card, :list_id, @lists.map{ |l| [l.title, l.id] }, {}, { class: 'form-control' } %>
      </div>
     <div class="text-center"><%= f.submit "更新する", class: "submitBtn" %></div>
    <% end %>
  </div>
</div>

app/views/card/new.html.erb
<h<div class="cardnewPgae">
  <div class='container'>
    <%= form_with model: @card, url: { action: :create }, html: { class: 'cardnewForm' } do |f| %>
      <%= f.hidden_field :list_id, value: @list.id %>
      <% if @card.errors.any? %>
        <p class="text-danger">タイトルは1～255文字以内で入力してください</p>
      <% end %>
      <div class="cardnewForm_title">
        <%= f.label :title %>
        <%= f.text_field :title, autofocus: true, class: "form-control", placeholder: "カード名" %>
      </div>
      <div class="cardnewForm_memo">
        <%= f.label :memo %>
        <%= f.text_area :memo, autofocus: true, class: "form-control", placeholder: "詳細" %>
      <div class="cardeditForm_memo">
        <label>レベル</label>
        <%= select :card, :category_id, @category.map{ |l| [l.name, l.id] }, {}, { class: 'form-control' } %>
      </div>
      <div class="text-center"><%= f.submit "作成する", class: "submitBtn" %></div>
      </div>
    <% end %>
  </div>
</div>

app/views/card/show.html.erb
<div class='carddetailPage'>
  <div class="container">
    <div class="cardContents">
      <div class="cardContents_title">
        <div>タイトル</div>
        <h2><%= @card.title %></h2>
      </div>
      <div class="cardContents_memo">
        <div>メモ</div>
        <div><%= @card.memo %></div>
      </div>
      <div class="cardContents_listStatus">
        <div>リスト名</div>
        <div><%= @card.list.title %></div>
      </div>
      <div class="cardContents_listStatus">
        <div>レベル</div>
        <div><%= @card.category.all %></div>
      </div>
      <div class="cardContents_btnArea">
        <%= link_to '編集する', edit_list_card_path(@card.list, @card), class: "edit_btn" %>
        <%= link_to '削除をする', list_card_path(@card.list, @card), class: "text-danger delete_btn", method: :delete, data: { confirm: "このカードを削除して大丈夫ですか?" } %>
      </div>
    </div>
  </div>
</div>
 <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="progress mt-3 fade" id="progress">
          <div class="progress-bar" role="progressbar"
               style="width: 0;" data-valuenow="0" data-valuemin="0" data-valuemax="100">
            0%
          </div>
        </div>
        <div class="mt-3 text-center">
          <button type="button" class="btn btn-outline-primary" id="btn">実行</button>
        </div>
      </div>
    </div>
  </div>

<!-- 以下プログレスバーのコード -->
<div id="progress-box">
   <div id="progress-bar">
   </div>
</div>
<script>
  var progress = 0;
var imgCount = $('img').length;
$("img").each(function(){
   var src = $(this).attr('src');
   $("<img>").attr('src',src).on('load',function(){
     progress++;
   });
});
setInterval(function(){
   $("#progress-bar").css({
     'width': (progress / imgCount) * 100 + '%'
   });
}, 1);
</script>


   <%= render partial: "card/animation" %>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-light" style="background-color: #e3f2fd;" fixed-top>
   <div><%= link_to "Task Quest", root_path, class: "nav-link" %></div>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="ナビゲーションの切替">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        <li class="nav-link"><%= current_user.name %>さん</li>
        <li><%= link_to "リストを作成", "list/new", class: "nav-link listNew" %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, class: "nav-link", method: :delete %></li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task03</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="alert alert-info"><%= flash[:notice] %></div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger"><%= flash[:alert] %></div>
    <% end %>



  <% if user_signed_in? %>
    <%= render partial: "layouts/header" %>
  <% end %>


    <%= yield %>
  </body>
</html>

app/views/list/create.html.erb
<h1>List#create</h1>
<p>Find me in app/views/list/create.html.erb</p>

app/views/list/edit.html.erb
<div class="listeditPage">
  <div class="container">
    <%= form_with model: @list, url: { action: :update }, html: { class: 'listForm' } do |f| %>
      <% if @list.errors.any? %>
        <p class="text-danger">タイトルは1～255文字以内で入力してください</p>
      <% end %>
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control listName", placeholder: "リスト名" %>
      <div class="text-center"><%= f.submit "編集する", class: "submitBtn" %></div>
    <% end %>
  </div>
</div>

app/views/list/new.html.erb
<div class="listnewPage">
  <div class="container">
    <%= form_with model: @list, url: { action: :create }, class: "new_list" do |f| %>
      <% if @list.errors.any? %>
        <p class="text-danger">タイトルは1～255文字以内で入力してください</p>
      <% end %>
      <%= f.label :title %>
      <%= f.text_field :title, autofocus: true, class: "form-control listName", placeholder: "リスト名" %>
      <div class="text-center"><%= f.submit "作成", class: "submitBtn" %></div>
    <% end %>
  </div>
</div>

app/views/top/index.html.erb
<div class="container">
  <div class="row">
    <% @lists.each do |list| %>
    <div class="col-sm-4">
      <div class="card  bg-light" mb-3" style="max-width: 18rem;">
        <div class="card-header ">
          <h4><%= list.title %></h4>
              <div><%= link_to(content_tag(:i, '', class: 'fas fa-pen-square'), edit_list_path(list)) %>
                  <%= link_to content_tag(:i, '', class: 'fas fa-trash'), list, method: :delete, data: { confirm: "#{list.title}を削除して大丈夫ですか?" } %>
              </div>
        </div>
        <div class="card card-body bg-light p-2">

        <% list.cards.each do |card| %>
            <%= link_to list_card_path(list, card), class: "cardDetail_link" do %>
          <div class="card bg-default mb-3" style="max-width: 18rem;">
            <h3 class="card_title"><%= card.title %></h3>
              <% if card.memo.size > 0 %>
                <div class="card_detail is-exist"><i class="fas fa-bars"></i></div>
              <% end %>
          </div>
          <% end %>
        <% end %>
          <div class="addCard">
            <i class="far fa-plus-square"></i>
            <%= link_to "さらにカードを追加", new_list_card_path(list), class: "addCard_link" %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>